version: '3'

services:
  certbot:
    image: certbot/dns-route53
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
